//generated by geneartor, delete this to regenerate.
import { WebSocketIo } from "pxprpc/backend";
import { Client } from "pxprpc/base";
import { RpcExtendClient1 } from "pxprpc/extend";

export var defaultServiceUrl='ws://'+location.host+'/pxprpc/2050';
export var defaultClient:RpcExtendClient1|null=null;

export async function getDefaultClient(){
    if(defaultClient===null){
        defaultClient=await new RpcExtendClient1(
            new Client(await new WebSocketIo().connect(defaultServiceUrl))).init();
    }
    return defaultClient;
}